
def get_all_grants():
    return [
        {
            "name": "Productivity Solutions Grant (PSG)",
            "type": "Digitalisation & Automation",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/for-local-companies/productivity-solutions-grant/overview",
            "description": "Supports companies in adopting IT solutions and equipment to enhance business processes.",
            "sectors": ["retail", "f&b", "logistics", "manufacturing", "professional services", "healthcare", "construction"],
            "max_revenue": 100_000_000,
            "max_staff": 200,
            "supported_goals": ["automation", "digitalisation", "productivity", "efficiency", "technology adoption"],
        },
        {
            "name": "Enterprise Development Grant (EDG)",
            "type": "Growth & Transformation",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/for-local-companies/enterprise-development-grant/overview",
            "description": "Helps Singapore companies grow and transform through innovation and market expansion.",
            "sectors": [],
            "max_revenue": None,
            "max_staff": None,
            "supported_goals": ["business transformation", "innovation", "market expansion", "capability building"],
        },
        {
            "name": "Market Readiness Assistance (MRA)",
            "type": "International Expansion",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/for-local-companies/market-readiness-assistance/overview",
            "description": "Supports SMEs taking their business overseas.",
            "sectors": [],
            "max_revenue": None,
            "max_staff": None,
            "supported_goals": ["overseas expansion", "market readiness", "export"],
        },
        {
            "name": "SkillsFuture Enterprise Credit (SFEC)",
            "type": "Skills Training & Capability Building",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/for-local-companies/skillsfuture-enterprise-credit",
            "description": "Incentivises employers to invest in enterprise and workforce transformation.",
            "sectors": [],
            "max_revenue": None,
            "max_staff": None,
            "supported_goals": ["training", "workforce development", "capability building"],
        },
        {
            "name": "Enterprise Financing Scheme (EFS) - Trade Loan",
            "type": "Working Capital Financing",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/enterprise-financing-scheme/trade-loan",
            "description": "Supports financing for trade activities.",
            "sectors": [],
            "max_revenue": None,
            "max_staff": None,
            "supported_goals": ["trade financing", "working capital"],
        },
        {
            "name": "Energy Efficiency Fund (E2F)",
            "type": "Green & Sustainability",
            "link": "https://www.nea.gov.sg/programmes-grants/grants-and-awards/energy-efficiency-fund",
            "description": "Supports projects that improve energy efficiency.",
            "sectors": ["manufacturing", "engineering", "facilities management"],
            "max_revenue": 500_000_000,
            "max_staff": 500,
            "supported_goals": ["sustainability", "energy efficiency", "green technology"],
        },
        {
            "name": "Startup SG Founder",
            "type": "Startup Funding",
            "link": "https://www.startupsg.gov.sg/programmes/for-startups/funding/sg-founder",
            "description": "Supports first-time entrepreneurs with mentorship and startup capital.",
            "sectors": [],
            "max_revenue": 1_000_000,
            "max_staff": 30,
            "supported_goals": ["startup funding", "entrepreneurship", "innovation"],
        },
        {
            "name": "Productivity Innovation Project Grant (PIP)",
            "type": "Innovation Grant",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/for-local-companies/productivity-innovation-project-grant",
            "description": "Supports the adoption of innovative solutions to increase productivity.",
            "sectors": ["manufacturing", "professional services", "logistics"],
            "max_revenue": 150_000_000,
            "max_staff": 300,
            "supported_goals": ["innovation", "productivity", "digitalisation"],
        },
        {
            "name": "Capability Transfer Programme (CTP)",
            "type": "Capability Building",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/for-local-companies/capability-transfer-programme",
            "description": "Supports knowledge transfer projects to build enterprise capabilities.",
            "sectors": [],
            "max_revenue": None,
            "max_staff": None,
            "supported_goals": ["capability building", "training", "knowledge transfer"],
        },
        {
            "name": "Business Improvement Fund (BIF)",
            "type": "Digitalisation & Training",
            "link": "https://www.enterprisesg.gov.sg/financial-assistance/grants/business-improvement-fund",
            "description": "Supports business improvements through digitalisation and training.",
            "sectors": ["retail", "f&b", "services"],
            "max_revenue": 50_000_000,
            "max_staff": 100,
            "supported_goals": ["digitalisation", "training", "process improvement"],
        },
        {
            "name": "Design Innovation Voucher",
            "type": "Innovation & Design",
            "link": "https://www.designsingapore.org/design-voucher",
            "description": "Supports companies seeking design expertise to innovate products and services.",
            "sectors": [],
            "max_revenue": 10_000_000,
            "max_staff": 50,
            "supported_goals": ["design", "innovation", "product development"],
        },
        {
            "name": "IT Support Grant",
            "type": "Digitalisation",
            "link": "https://www.imda.gov.sg/programme-listing/infocomm-media-development-authority-it-support-grant",
            "description": "Supports adoption of IT solutions and consultancy services.",
            "sectors": ["professional services", "retail", "f&b", "logistics"],
            "max_revenue": 30_000_000,
            "max_staff": 100,
            "supported_goals": ["digitalisation", "technology adoption"],
        },
        {
            "name": "Skills Development Fund (SDF)",
            "type": "Training & Capability Building",
            "link": "https://www.skillsfuture.gov.sg/funding-and-credits",
            "description": "Supports workforce training and upgrading.",
            "sectors": [],
            "max_revenue": None,
            "max_staff": None,
            "supported_goals": ["training", "skills upgrading", "workforce development"],
        },
    ]
